const RESOURCE_MODULES = Object.freeze([
  {
    key: "employers",
    label: "Employer",
    collection: "employers",
    route: "/employers",
    searchableFields: ["companyName", "registrationNumber", "companyEmail", "phone", "website"],
    actions: ["configure"],
  },
  {
    key: "branches",
    label: "Branch",
    collection: "branches",
    route: "/employers/branches",
    searchableFields: ["name", "code", "address", "location"],
    actions: ["deactivate"],
  },
  {
    key: "employees",
    label: "Employee",
    collection: "employees",
    route: "/employees",
    searchableFields: ["employeeId", "fullName", "email", "phone", "department", "position"],
    actions: ["deactivate", "suspend", "terminate", "transfer", "promote", "reset-password"],
  },
  {
    key: "interns",
    label: "Intern",
    collection: "interns",
    route: "/interns",
    searchableFields: ["internId", "name", "institution", "course", "department", "supervisor"],
    actions: ["register", "complete", "terminate", "generate-document"],
  },
  {
    key: "nysc",
    label: "NYSC Member",
    collection: "nysc_members",
    route: "/nysc",
    searchableFields: ["nyscId", "stateCode", "callUpNumber", "name", "institution", "department"],
    actions: ["transfer", "complete", "generate-acceptance-letter", "generate-completion-letter"],
  },
  {
    key: "departments",
    label: "Department",
    collection: "departments",
    route: "/departments",
    searchableFields: ["name", "code", "head", "description"],
    actions: ["assign-head", "assign-members"],
  },
  {
    key: "leave",
    label: "Leave Request",
    collection: "leave_requests",
    route: "/leave",
    searchableFields: ["employeeName", "employeeId", "type", "status", "reason"],
    actions: ["approve", "reject", "cancel"],
  },
  {
    key: "leave-types",
    label: "Leave Type",
    collection: "leave_types",
    route: "/leave/types",
    searchableFields: ["name", "code", "description"],
    actions: ["configure"],
  },
  {
    key: "salary-increments",
    label: "Salary Increment",
    collection: "salary_increments",
    route: "/salary-increments",
    searchableFields: ["employeeName", "employeeId", "reason", "status"],
    actions: ["approve", "reject"],
    transactional: true,
  },
  {
    key: "promotions",
    label: "Promotion",
    collection: "promotions",
    route: "/promotions",
    searchableFields: ["employeeName", "employeeId", "currentPosition", "newPosition", "status"],
    actions: ["approve", "reject"],
    transactional: true,
  },
  {
    key: "meetings",
    label: "Meeting",
    collection: "meetings",
    route: "/meetings",
    searchableFields: ["title", "organizer", "location", "agenda", "status"],
    actions: ["schedule", "cancel", "minutes"],
  },
  {
    key: "tasks",
    label: "Task",
    collection: "tasks",
    route: "/tasks",
    searchableFields: ["title", "description", "assignedTo", "department", "priority", "status"],
    actions: ["assign", "reassign", "review", "approve-completion"],
  },
  {
    key: "targets",
    label: "Target",
    collection: "targets",
    route: "/targets",
    searchableFields: ["title", "type", "department", "employeeName", "status"],
    actions: ["assign", "track", "review"],
  },
  {
    key: "payroll",
    label: "Payroll",
    collection: "payroll",
    route: "/payroll",
    searchableFields: ["period", "status", "employeeName", "employeeId"],
    actions: ["review", "approve", "process", "generate-payslips"],
    transactional: true,
    softDeleteOnly: true,
  },
  {
    key: "purchases",
    label: "Purchase",
    collection: "purchase_requests",
    route: "/purchases",
    searchableFields: ["title", "requestNumber", "vendor", "department", "status"],
    actions: ["approve", "reject", "create-order", "track-delivery", "track-payment"],
    transactional: true,
    softDeleteOnly: true,
  },
  {
    key: "bills",
    label: "Bill",
    collection: "bills",
    route: "/bills",
    searchableFields: ["billNumber", "vendor", "description", "category", "paymentStatus"],
    actions: ["approve", "pay", "cancel", "track", "export"],
    transactional: true,
    softDeleteOnly: true,
  },
  {
    key: "expenses",
    label: "Expense",
    collection: "expenses",
    route: "/expenses",
    searchableFields: ["title", "employeeName", "department", "category", "status"],
    actions: ["approve", "reject", "export"],
    transactional: true,
    softDeleteOnly: true,
  },
  {
    key: "vendors",
    label: "Vendor",
    collection: "vendors",
    route: "/vendors",
    searchableFields: ["name", "email", "phone", "category", "status"],
    actions: ["deactivate"],
  },
  {
    key: "events",
    label: "Event",
    collection: "events",
    route: "/events",
    searchableFields: ["title", "location", "status", "description"],
    actions: ["cancel", "invite", "notify"],
  },
  {
    key: "discipline",
    label: "Disciplinary Case",
    collection: "disciplinary_cases",
    route: "/discipline",
    searchableFields: ["caseNumber", "employeeName", "action", "status", "summary"],
    actions: ["add-evidence", "issue-warning", "suspend-employee", "resolve", "close"],
    sensitive: true,
  },
  {
    key: "announcements",
    label: "Announcement",
    collection: "announcements",
    route: "/announcements",
    searchableFields: ["title", "body", "target", "status"],
    actions: ["schedule", "pin", "expire"],
  },
  {
    key: "reports",
    label: "Report",
    collection: "reports",
    route: "/reports",
    searchableFields: ["title", "type", "status", "format"],
    collectionActions: ["generate"],
    actions: ["generate", "export"],
  },
  {
    key: "users",
    label: "User",
    collection: "users",
    route: "/users",
    searchableFields: ["name", "email", "role", "status"],
    actions: ["deactivate", "reset-password", "force-password-reset", "force-logout"],
  },
  {
    key: "roles",
    label: "Role",
    collection: "roles",
    route: "/roles",
    searchableFields: ["name", "key", "description"],
    actions: ["assign-permissions", "remove-permissions", "assign-users"],
  },
  {
    key: "permissions",
    label: "Permission",
    collection: "permissions",
    route: "/permissions",
    searchableFields: ["key", "module", "action", "description"],
    actions: [],
  },
  {
    key: "integrations",
    label: "Integration",
    collection: "integrations",
    route: "/integrations",
    searchableFields: ["name", "provider", "status"],
    actions: ["test-connection", "sync"],
    sensitive: true,
  },
  {
    key: "email-configurations",
    label: "Email Configuration",
    collection: "email_configurations",
    route: "/email-configurations",
    searchableFields: ["smtpHost", "senderEmail", "senderName", "status"],
    actions: ["test-connection", "send-test-email"],
    sensitive: true,
  },
  {
    key: "notification-configurations",
    label: "Notification Configuration",
    collection: "notification_configurations",
    route: "/notification-configurations",
    searchableFields: ["name", "channel", "trigger", "status"],
    actions: ["test", "enable", "disable"],
  },
  {
    key: "document-templates",
    label: "Document Template",
    collection: "document_templates",
    route: "/document-templates",
    searchableFields: ["name", "type", "status"],
    actions: ["generate-pdf"],
  },
  {
    key: "backups",
    label: "Backup",
    collection: "backups",
    route: "/backups",
    searchableFields: ["backupId", "status", "storage", "createdBy"],
    actions: ["restore", "download"],
    sensitive: true,
    softDeleteOnly: true,
  },
  {
    key: "system-health",
    label: "System Health",
    collection: "system_health",
    route: "/system-health",
    searchableFields: ["service", "status", "message"],
    actions: ["check"],
  },
  {
    key: "system-settings",
    label: "System Setting",
    collection: "system_settings",
    route: "/system-settings",
    searchableFields: ["key", "section", "value"],
    actions: ["configure"],
    sensitive: true,
  },
  {
    key: "technical-audit",
    label: "Technical Audit Log",
    collection: "technical_audit_logs",
    route: "/technical-audit",
    searchableFields: ["requestId", "endpoint", "service", "error", "method"],
    actions: [],
    immutable: true,
  },
  {
    key: "operational-audit",
    label: "Operational Audit Log",
    collection: "operational_audit_logs",
    route: "/operational-audit",
    searchableFields: ["action", "module", "recordId", "user"],
    actions: [],
    immutable: true,
  },
  {
    key: "help",
    label: "Help Center",
    collection: "help_articles",
    route: "/help",
    searchableFields: ["title", "category", "body"],
    actions: ["publish"],
  },
]);

const SUPER_ADMIN_NAVIGATION = Object.freeze([
  "overview",
  "employers",
  "employees",
  "interns",
  "nysc",
  "departments",
  "leave",
  "salary-increments",
  "promotions",
  "meetings",
  "tasks",
  "targets",
  "payroll",
  "purchases",
  "bills",
  "expenses",
  "vendors",
  "events",
  "discipline",
  "announcements",
  "reports",
  "operational-audit",
  "system-management",
  "users",
  "roles",
  "permissions",
  "security",
  "integrations",
  "email-configurations",
  "notification-configurations",
  "document-templates",
  "backups",
  "system-health",
  "technical-audit",
  "profile",
  "help",
  "settings",
  "sign-out",
]);

function getResourceModule(key) {
  return RESOURCE_MODULES.find((moduleDefinition) => moduleDefinition.key === key) || null;
}

module.exports = { RESOURCE_MODULES, SUPER_ADMIN_NAVIGATION, getResourceModule };
