const ENTERPRISE_MODULE_KEYS = [
  "employer",
  "employee",
  "intern",
  "nysc",
  "department",
  "leave",
  "salary",
  "promotion",
  "meeting",
  "task",
  "target",
  "payroll",
  "purchase",
  "bill",
  "expense",
  "vendor",
  "event",
  "discipline",
  "announcement",
  "report",
  "operational_audit",
  "system",
  "user",
  "role",
  "permission",
  "security",
  "integration",
  "email",
  "notification",
  "document",
  "backup",
  "health",
  "technical_audit",
  "profile",
  "help",
  "setting",
];

const PERMISSION_ACTIONS = ["view", "create", "update", "delete", "approve", "reject", "export", "manage", "configure"];

function buildEnterprisePermissions() {
  return ENTERPRISE_MODULE_KEYS.reduce((permissions, moduleKey) => {
    for (const action of PERMISSION_ACTIONS) {
      const key = `${moduleKey}.${action}`.toUpperCase().replace(/[^A-Z0-9]+/g, "_");
      permissions[key] = `${moduleKey}.${action}`;
    }

    return permissions;
  }, {});
}

const PERMISSIONS = Object.freeze({
  ...buildEnterprisePermissions(),
  DEPARTMENT_VIEW: "department.view",
  DEPARTMENT_CREATE: "department.create",
  DEPARTMENT_UPDATE: "department.update",
  DEPARTMENT_DELETE: "department.delete",
  DEPARTMENT_ACTIVATE: "department.activate",
  DEPARTMENT_DEACTIVATE: "department.deactivate",
  DEPARTMENT_ASSIGN_HOD: "department.assign_hod",
  DEPARTMENT_ASSIGN_ASSISTANT_HOD: "department.assign_assistant_hod",
  DEPARTMENT_VIEW_EMPLOYEES: "department.view_employees",
  DEPARTMENT_TRANSFER_EMPLOYEE: "department.transfer_employee",
  DEPARTMENT_VIEW_PAYROLL: "department.view_payroll",
  DEPARTMENT_VIEW_EXPENSES: "department.view_expenses",
  DEPARTMENT_VIEW_PURCHASES: "department.view_purchases",
  DEPARTMENT_VIEW_REPORTS: "department.view_reports",
  DEPARTMENT_EXPORT: "department.export",
  DEPARTMENT_MANAGE_DOCUMENTS: "department.manage_documents",
  CREATE_EMPLOYEE: "employees:create",
  EDIT_EMPLOYEE: "employees:update",
  DELETE_EMPLOYEE: "employees:delete",
  VIEW_EMPLOYEE: "employees:view",
  MANAGE_DEPARTMENTS: "departments:manage",
  ASSIGN_TASKS: "tasks:assign",
  DELETE_TASKS: "tasks:delete",
  APPROVE_LEAVE: "leave:approve",
  REJECT_LEAVE: "leave:reject",
  LEAVE_VIEW: "leave.view",
  LEAVE_CREATE: "leave.create",
  LEAVE_APPROVE: "leave.approve",
  LEAVE_REJECT: "leave.reject",
  LEAVE_CANCEL: "leave.cancel",
  LEAVE_WITHDRAW: "leave.withdraw",
  LEAVE_MANAGE_TYPES: "leave.manage_types",
  LEAVE_MANAGE_POLICIES: "leave.manage_policies",
  LEAVE_MANAGE_BALANCES: "leave.manage_balances",
  LEAVE_VIEW_ALL: "leave.view_all",
  LEAVE_VIEW_DEPARTMENT: "leave.view_department",
  LEAVE_VIEW_OWN: "leave.view_own",
  LEAVE_EXPORT: "leave.export",
  LEAVE_REPORTS: "leave.reports",
  MEETING_VIEW: "meeting.view",
  MEETING_VIEW_ALL: "meeting.view_all",
  MEETING_CREATE: "meeting.create",
  MEETING_UPDATE: "meeting.update",
  MEETING_CANCEL: "meeting.cancel",
  MEETING_POSTPONE: "meeting.postpone",
  MEETING_MANAGE_PARTICIPANTS: "meeting.manage_participants",
  MEETING_MANAGE_AGENDA: "meeting.manage_agenda",
  MEETING_MANAGE_MINUTES: "meeting.manage_minutes",
  MEETING_MANAGE_ATTENDANCE: "meeting.manage_attendance",
  MEETING_MANAGE_ACTION_ITEMS: "meeting.manage_action_items",
  MEETING_MANAGE_TYPES: "meeting.manage_types",
  MEETING_MANAGE_ROOMS: "meeting.manage_rooms",
  MEETING_VIEW_REPORTS: "meeting.view_reports",
  MEETING_EXPORT: "meeting.export",
  TARGET_VIEW: "target.view",
  TARGET_VIEW_ALL: "target.view_all",
  TARGET_CREATE: "target.create",
  TARGET_UPDATE: "target.update",
  TARGET_DELETE: "target.delete",
  TARGET_ASSIGN: "target.assign",
  TARGET_UPDATE_PROGRESS: "target.update_progress",
  TARGET_MANAGE_MILESTONES: "target.manage_milestones",
  TARGET_MANAGE_REVIEWS: "target.manage_reviews",
  TARGET_VIEW_REPORTS: "target.view_reports",
  TARGET_EXPORT: "target.export",
  PAYROLL_VIEW: "payroll.view",
  PAYROLL_VIEW_ALL: "payroll.view_all",
  PAYROLL_CREATE: "payroll.create",
  PAYROLL_CALCULATE: "payroll.calculate",
  PAYROLL_UPDATE: "payroll.update",
  PAYROLL_APPROVE: "payroll.approve",
  PAYROLL_REJECT: "payroll.reject",
  PAYROLL_PROCESS_PAYMENT: "payroll.process_payment",
  PAYROLL_RETRY_PAYMENT: "payroll.retry_payment",
  PAYROLL_LOCK: "payroll.lock",
  PAYROLL_CANCEL: "payroll.cancel",
  PAYROLL_VIEW_PAYSLIPS: "payroll.view_payslips",
  PAYROLL_MANAGE_SALARY: "payroll.manage_salary",
  PAYROLL_MANAGE_DEDUCTIONS: "payroll.manage_deductions",
  PAYROLL_MANAGE_TAX_RULES: "payroll.manage_tax_rules",
  PAYROLL_MANAGE_STATUTORY_RULES: "payroll.manage_statutory_rules",
  PAYROLL_VIEW_REPORTS: "payroll.view_reports",
  PAYROLL_EXPORT: "payroll.export",
  PURCHASE_REQUEST_VIEW: "purchase_request.view",
  PURCHASE_REQUEST_VIEW_ALL: "purchase_request.view_all",
  PURCHASE_REQUEST_CREATE: "purchase_request.create",
  PURCHASE_REQUEST_UPDATE: "purchase_request.update",
  PURCHASE_REQUEST_SUBMIT: "purchase_request.submit",
  PURCHASE_REQUEST_REVIEW: "purchase_request.review",
  PURCHASE_REQUEST_APPROVE: "purchase_request.approve",
  PURCHASE_REQUEST_REJECT: "purchase_request.reject",
  PURCHASE_REQUEST_CANCEL: "purchase_request.cancel",
  PURCHASE_REQUEST_ASSIGN_VENDOR: "purchase_request.assign_vendor",
  PURCHASE_REQUEST_CREATE_ORDER: "purchase_request.create_order",
  PURCHASE_REQUEST_RECEIVE: "purchase_request.receive",
  PURCHASE_REQUEST_COMMENT: "purchase_request.comment",
  PURCHASE_REQUEST_UPLOAD: "purchase_request.upload",
  PURCHASE_REQUEST_VIEW_REPORTS: "purchase_request.view_reports",
  PURCHASE_REQUEST_EXPORT: "purchase_request.export",
  BILL_VIEW: "bill.view",
  BILL_VIEW_ALL: "bill.view_all",
  BILL_CREATE: "bill.create",
  BILL_UPDATE: "bill.update",
  BILL_SUBMIT: "bill.submit",
  BILL_REVIEW: "bill.review",
  BILL_APPROVE: "bill.approve",
  BILL_REJECT: "bill.reject",
  BILL_DISPUTE: "bill.dispute",
  BILL_SCHEDULE_PAYMENT: "bill.schedule_payment",
  BILL_PAY: "bill.pay",
  BILL_UPLOAD: "bill.upload",
  BILL_COMMENT: "bill.comment",
  BILL_EXPORT: "bill.export",
  BILL_DELETE: "bill.delete",
  MANAGE_SALARY: "salary:manage",
  MANAGE_PROMOTIONS: "promotions:manage",
  MANAGE_MEETINGS: "meetings:manage",
  VIEW_REPORTS: "reports:view",
  MANAGE_REPORTS: "reports:manage",
  MANAGE_SETTINGS: "settings:manage",
  BACKUP: "backup:manage",
  RESTORE: "backup:restore",
  VIEW_AUDIT_LOGS: "audit:view",
  MANAGE_ROLES: "roles:manage",
  MANAGE_PERMISSIONS: "permissions:manage",
  SYSTEM_CONFIGURATION: "system:configure",
  VIEW_DASHBOARD: "dashboard:view",
  MANAGE_ATTENDANCE: "attendance:manage",
  MANAGE_ANNOUNCEMENTS: "announcements:manage",
  MANAGE_NOTIFICATIONS: "notifications:manage",
  MANAGE_FILES: "files:manage",
  GLOBAL_SEARCH: "search:global",
});

const ROLE_DEFINITIONS = Object.freeze({
  superadmin: {
    key: "superadmin",
    name: "Super Admin",
    rank: 1,
    permissions: Object.values(PERMISSIONS),
  },
  admin: {
    key: "admin",
    name: "Admin",
    rank: 2,
    permissions: Object.values(PERMISSIONS).filter((permission) => permission !== PERMISSIONS.RESTORE),
  },
  department_manager: {
    key: "department_manager",
    name: "Department Manager",
    rank: 3,
    permissions: [
      PERMISSIONS.VIEW_DASHBOARD,
      PERMISSIONS.VIEW_EMPLOYEE,
      PERMISSIONS.EDIT_EMPLOYEE,
      PERMISSIONS.MANAGE_DEPARTMENTS,
      PERMISSIONS.ASSIGN_TASKS,
      PERMISSIONS.APPROVE_LEAVE,
      PERMISSIONS.REJECT_LEAVE,
      PERMISSIONS.LEAVE_VIEW_OWN,
      PERMISSIONS.LEAVE_CREATE,
      PERMISSIONS.LEAVE_WITHDRAW,
      PERMISSIONS.LEAVE_VIEW_DEPARTMENT,
      PERMISSIONS.LEAVE_APPROVE,
      PERMISSIONS.LEAVE_REJECT,
      PERMISSIONS.MANAGE_MEETINGS,
      PERMISSIONS.MEETING_VIEW,
      PERMISSIONS.MEETING_VIEW_ALL,
      PERMISSIONS.MEETING_CREATE,
      PERMISSIONS.MEETING_UPDATE,
      PERMISSIONS.MEETING_CANCEL,
      PERMISSIONS.MEETING_POSTPONE,
      PERMISSIONS.MEETING_MANAGE_PARTICIPANTS,
      PERMISSIONS.MEETING_MANAGE_AGENDA,
      PERMISSIONS.MEETING_MANAGE_MINUTES,
      PERMISSIONS.MEETING_MANAGE_ATTENDANCE,
      PERMISSIONS.MEETING_MANAGE_ACTION_ITEMS,
      PERMISSIONS.MEETING_VIEW_REPORTS,
      PERMISSIONS.TARGET_VIEW,
      PERMISSIONS.TARGET_VIEW_ALL,
      PERMISSIONS.TARGET_CREATE,
      PERMISSIONS.TARGET_UPDATE,
      PERMISSIONS.TARGET_DELETE,
      PERMISSIONS.TARGET_ASSIGN,
      PERMISSIONS.TARGET_UPDATE_PROGRESS,
      PERMISSIONS.TARGET_MANAGE_MILESTONES,
      PERMISSIONS.TARGET_MANAGE_REVIEWS,
      PERMISSIONS.TARGET_VIEW_REPORTS,
      PERMISSIONS.TARGET_EXPORT,
      PERMISSIONS.PAYROLL_VIEW,
      PERMISSIONS.PAYROLL_VIEW_ALL,
      PERMISSIONS.PAYROLL_CREATE,
      PERMISSIONS.PAYROLL_CALCULATE,
      PERMISSIONS.PAYROLL_UPDATE,
      PERMISSIONS.PAYROLL_APPROVE,
      PERMISSIONS.PAYROLL_REJECT,
      PERMISSIONS.PAYROLL_PROCESS_PAYMENT,
      PERMISSIONS.PAYROLL_RETRY_PAYMENT,
      PERMISSIONS.PAYROLL_LOCK,
      PERMISSIONS.PAYROLL_CANCEL,
      PERMISSIONS.PAYROLL_VIEW_PAYSLIPS,
      PERMISSIONS.PAYROLL_MANAGE_SALARY,
      PERMISSIONS.PAYROLL_MANAGE_DEDUCTIONS,
      PERMISSIONS.PAYROLL_MANAGE_TAX_RULES,
      PERMISSIONS.PAYROLL_MANAGE_STATUTORY_RULES,
      PERMISSIONS.PAYROLL_VIEW_REPORTS,
      PERMISSIONS.PAYROLL_EXPORT,
      PERMISSIONS.PURCHASE_REQUEST_VIEW,
      PERMISSIONS.PURCHASE_REQUEST_VIEW_ALL,
      PERMISSIONS.PURCHASE_REQUEST_CREATE,
      PERMISSIONS.PURCHASE_REQUEST_UPDATE,
      PERMISSIONS.PURCHASE_REQUEST_SUBMIT,
      PERMISSIONS.PURCHASE_REQUEST_REVIEW,
      PERMISSIONS.PURCHASE_REQUEST_APPROVE,
      PERMISSIONS.PURCHASE_REQUEST_REJECT,
      PERMISSIONS.PURCHASE_REQUEST_CANCEL,
      PERMISSIONS.PURCHASE_REQUEST_ASSIGN_VENDOR,
      PERMISSIONS.PURCHASE_REQUEST_CREATE_ORDER,
      PERMISSIONS.PURCHASE_REQUEST_RECEIVE,
      PERMISSIONS.PURCHASE_REQUEST_COMMENT,
      PERMISSIONS.PURCHASE_REQUEST_UPLOAD,
      PERMISSIONS.PURCHASE_REQUEST_VIEW_REPORTS,
      PERMISSIONS.PURCHASE_REQUEST_EXPORT,
      PERMISSIONS.BILL_VIEW,
      PERMISSIONS.BILL_CREATE,
      PERMISSIONS.BILL_UPDATE,
      PERMISSIONS.BILL_SUBMIT,
      PERMISSIONS.BILL_REVIEW,
      PERMISSIONS.BILL_APPROVE,
      PERMISSIONS.BILL_REJECT,
      PERMISSIONS.BILL_DISPUTE,
      PERMISSIONS.BILL_UPLOAD,
      PERMISSIONS.BILL_COMMENT,
      PERMISSIONS.BILL_EXPORT,
      PERMISSIONS.VIEW_REPORTS,
      PERMISSIONS.MANAGE_ATTENDANCE,
      PERMISSIONS.MANAGE_ANNOUNCEMENTS,
      PERMISSIONS.MANAGE_NOTIFICATIONS,
      PERMISSIONS.GLOBAL_SEARCH,
    ],
  },
  team_leader: {
    key: "team_leader",
    name: "Team Leader",
    rank: 4,
    permissions: [
      PERMISSIONS.VIEW_DASHBOARD,
      PERMISSIONS.VIEW_EMPLOYEE,
      PERMISSIONS.ASSIGN_TASKS,
      PERMISSIONS.MANAGE_MEETINGS,
      PERMISSIONS.MEETING_VIEW,
      PERMISSIONS.MEETING_CREATE,
      PERMISSIONS.MEETING_UPDATE,
      PERMISSIONS.MEETING_CANCEL,
      PERMISSIONS.MEETING_POSTPONE,
      PERMISSIONS.MEETING_MANAGE_PARTICIPANTS,
      PERMISSIONS.MEETING_MANAGE_AGENDA,
      PERMISSIONS.MEETING_MANAGE_MINUTES,
      PERMISSIONS.MEETING_MANAGE_ATTENDANCE,
      PERMISSIONS.MEETING_MANAGE_ACTION_ITEMS,
      PERMISSIONS.TARGET_VIEW,
      PERMISSIONS.TARGET_CREATE,
      PERMISSIONS.TARGET_UPDATE,
      PERMISSIONS.TARGET_ASSIGN,
      PERMISSIONS.TARGET_UPDATE_PROGRESS,
      PERMISSIONS.TARGET_MANAGE_MILESTONES,
      PERMISSIONS.TARGET_VIEW_REPORTS,
      PERMISSIONS.PAYROLL_VIEW,
      PERMISSIONS.PAYROLL_VIEW_PAYSLIPS,
      PERMISSIONS.PAYROLL_VIEW_REPORTS,
      PERMISSIONS.PURCHASE_REQUEST_VIEW,
      PERMISSIONS.PURCHASE_REQUEST_CREATE,
      PERMISSIONS.PURCHASE_REQUEST_UPDATE,
      PERMISSIONS.PURCHASE_REQUEST_SUBMIT,
      PERMISSIONS.PURCHASE_REQUEST_REVIEW,
      PERMISSIONS.PURCHASE_REQUEST_APPROVE,
      PERMISSIONS.PURCHASE_REQUEST_REJECT,
      PERMISSIONS.PURCHASE_REQUEST_CANCEL,
      PERMISSIONS.PURCHASE_REQUEST_COMMENT,
      PERMISSIONS.PURCHASE_REQUEST_UPLOAD,
      PERMISSIONS.PURCHASE_REQUEST_VIEW_REPORTS,
      PERMISSIONS.BILL_VIEW,
      PERMISSIONS.BILL_CREATE,
      PERMISSIONS.BILL_SUBMIT,
      PERMISSIONS.BILL_REVIEW,
      PERMISSIONS.BILL_APPROVE,
      PERMISSIONS.BILL_REJECT,
      PERMISSIONS.BILL_COMMENT,
      PERMISSIONS.BILL_UPLOAD,
      PERMISSIONS.VIEW_REPORTS,
      PERMISSIONS.MANAGE_ATTENDANCE,
      PERMISSIONS.GLOBAL_SEARCH,
    ],
  },
  employee: {
    key: "employee",
    name: "Employee",
    rank: 5,
    permissions: [
      PERMISSIONS.VIEW_DASHBOARD,
      PERMISSIONS.VIEW_EMPLOYEE,
      PERMISSIONS.LEAVE_VIEW_OWN,
      PERMISSIONS.LEAVE_CREATE,
      PERMISSIONS.LEAVE_WITHDRAW,
      PERMISSIONS.MANAGE_MEETINGS,
      PERMISSIONS.MEETING_VIEW,
      PERMISSIONS.TARGET_VIEW,
      PERMISSIONS.TARGET_UPDATE_PROGRESS,
      PERMISSIONS.PAYROLL_VIEW_PAYSLIPS,
      PERMISSIONS.PURCHASE_REQUEST_VIEW,
      PERMISSIONS.PURCHASE_REQUEST_CREATE,
      PERMISSIONS.PURCHASE_REQUEST_SUBMIT,
      PERMISSIONS.PURCHASE_REQUEST_CANCEL,
      PERMISSIONS.PURCHASE_REQUEST_COMMENT,
      PERMISSIONS.PURCHASE_REQUEST_UPLOAD,
      PERMISSIONS.BILL_VIEW,
      PERMISSIONS.BILL_COMMENT,
      PERMISSIONS.BILL_UPLOAD,
      PERMISSIONS.GLOBAL_SEARCH,
    ],
  },
});

function getRoleDefinition(role) {
  return ROLE_DEFINITIONS[role] || null;
}

function getRolePermissions(role) {
  const definition = getRoleDefinition(role);
  return definition ? definition.permissions : [];
}

function hasPermission(user, permission) {
  if (!user) {
    return false;
  }

  const rolePermissions = getRolePermissions(user.role);
  const directPermissions = Array.isArray(user.permissions) ? user.permissions : [];
  return rolePermissions.includes(permission) || directPermissions.includes(permission);
}

module.exports = { PERMISSIONS, ROLE_DEFINITIONS, getRoleDefinition, getRolePermissions, hasPermission };
