const ENTERPRISE_MODULE_KEYS = [
  "employer",
  "employee",
  "employee_exit",
  "intern",
  "nysc",
  "department",
  "leave",
  "salary",
  "promotion",
  "meeting",
  "task",
  "target",
  "attendance",
  "payroll",
  "purchase",
  "bill",
  "expense",
  "vendor",
  "event",
  "discipline",
  "announcement",
  "report",
  "operational_audit",
  "system",
  "user",
  "role",
  "permission",
  "security",
  "integration",
  "email",
  "notification",
  "document",
  "backup",
  "health",
  "technical_audit",
  "profile",
  "secretary",
  "accountant",
  "email_request",
  "calendar",
  "management_task",
  "reminder",
  "payment",
  "invoice",
  "reconciliation",
  "help",
  "setting",
];

const PERMISSION_ACTIONS = ["view", "create", "update", "delete", "approve", "reject", "export", "manage", "configure"];
const ARCHITECTURE_PERMISSIONS = [
  "overview.view",
  "employees.view",
  "employees.create",
  "employees.update",
  "employees.delete",
  "employees.archive",
  "employees.view_sensitive",
  "employees.documents.view",
  "employees.documents.create",
  "employees.documents.update",
  "employees.documents.delete",
  "employee_exits.view",
  "employee_exits.create",
  "employee_exits.update",
  "employee_exits.approve",
  "employee_exits.complete",
  "employee_exits.cancel",
  "employee_documents.view",
  "employee_documents.create",
  "employee_documents.update",
  "employee_documents.delete",
  "onboarding.view",
  "onboarding.create",
  "onboarding.update",
  "onboarding.review",
  "onboarding.approve",
  "confirmation.view",
  "confirmation.review",
  "confirmation.approve",
  "confirmation.extend",
  "departments.view",
  "departments.create",
  "departments.update",
  "departments.delete",
  "positions.view",
  "positions.create",
  "positions.update",
  "positions.delete",
  "leave.view",
  "leave.request",
  "leave.approve",
  "leave.reject",
  "leave.manage",
  "leave.view_team",
  "promotions.view",
  "promotions.create",
  "promotions.approve",
  "promotions.reject",
  "promotions.manage",
  "salary.view",
  "salary.create",
  "salary.update",
  "salary.review",
  "salary.approve",
  "salary.reject",
  "salary_increments.view",
  "salary_increments.create",
  "salary_increments.approve",
  "salary_increments.reject",
  "salary_increments.manage",
  "meetings.view",
  "meetings.create",
  "meetings.update",
  "meetings.delete",
  "meetings.manage",
  "attendance.view",
  "attendance.manage",
  "attendance.correct",
  "attendance.check_in",
  "attendance.locations.view",
  "attendance.locations.manage",
  "attendance.schedules.view",
  "attendance.schedules.manage",
  "performance.view",
  "performance.create",
  "performance.review",
  "performance.approve",
  "tasks.view",
  "tasks.create",
  "tasks.assign",
  "tasks.update",
  "tasks.delete",
  "tasks.manage",
  "targets.view",
  "targets.create",
  "targets.assign",
  "targets.update",
  "targets.approve",
  "targets.manage",
  "payroll.view",
  "payroll.create",
  "payroll.process",
  "payroll.approve",
  "payroll.manage",
  "payroll.export",
  "purchases.view",
  "purchases.create",
  "purchases.approve",
  "purchases.reject",
  "purchases.manage",
  "finance.view",
  "finance.create",
  "finance.approve",
  "procurement.view",
  "procurement.create",
  "procurement.approve",
  "bills.view",
  "bills.create",
  "bills.approve",
  "bills.pay",
  "bills.manage",
  "expenses.view",
  "expenses.create",
  "expenses.approve",
  "expenses.reject",
  "expenses.manage",
  "expenses.export",
  "vendors.view",
  "vendors.create",
  "vendors.update",
  "vendors.delete",
  "vendors.manage",
  "events.view",
  "events.create",
  "events.update",
  "events.delete",
  "events.publish",
  "events.manage",
  "discipline.view",
  "discipline.create",
  "discipline.update",
  "discipline.close",
  "discipline.manage",
  "nysc_interns.view",
  "nysc_interns.create",
  "nysc_interns.update",
  "nysc_interns.delete",
  "nysc_interns.manage",
  "announcements.view",
  "announcements.create",
  "announcements.publish",
  "announcements.pin",
  "announcements.delete",
  "announcements.manage",
  "reports.view",
  "reports.create",
  "reports.export",
  "reports.manage",
  "audit_logs.view",
  "audit_logs.export",
  "system_management.view",
  "system_management.manage",
  "users.view",
  "users.create",
  "users.update",
  "users.lock",
  "users.unlock",
  "users.activate",
  "users.deactivate",
  "users.delete",
  "users.revoke_sessions",
  "users.reset_password",
  "roles.view",
  "roles.create",
  "roles.update",
  "roles.delete",
  "roles.assign_permissions",
  "security.view",
  "security.update",
  "security.manage",
  "security.manage_mfa",
  "security.manage_sessions",
  "security.unlock_accounts",
  "security.manage_maintenance",
  "security.view_security_logs",
  "integrations.view",
  "integrations.manage",
  "view_integrations",
  "manage_integrations",
  "connect_integrations",
  "disconnect_integrations",
  "configure_integrations",
  "test_integrations",
  "paystack.payments",
  "email_config.view",
  "email_config.manage",
  "email_config.update",
  "email_config.test",
  "email_config.templates",
  "email.send",
  "notification_config.view",
  "notification_config.manage",
  "notification_config.update",
  "notification_config.rules",
  "notification_config.logs",
  "notifications.view_all",
  "notifications.view",
  "notifications.manage",
  "document_templates.view",
  "document_templates.create",
  "document_templates.update",
  "document_templates.delete",
  "backups.view",
  "backups.create",
  "backups.restore",
  "backups.delete",
  "system_health.view",
  "technical_audit_logs.view",
  "profile.view",
  "profile.update",
  "secretary.dashboard.view",
  "email_requests.view",
  "email_requests.create",
  "email_requests.update",
  "email_requests.review",
  "email_requests.approve",
  "email_requests.reject",
  "email_requests.cancel",
  "email_requests.retry",
  "email_requests.check_availability",
  "email_requests.create_company_email",
  "email_requests.follow_up",
  "company_email.view",
  "company_email.search",
  "company_email.edit_address",
  "company_email.suspend",
  "company_email.reactivate",
  "company_email.request_deactivation",
  "company_email.view_history",
  "calendar.view",
  "calendar.create",
  "calendar.update",
  "calendar.delete",
  "management_tasks.view",
  "management_tasks.create",
  "management_tasks.update",
  "management_tasks.assign",
  "reminders.view",
  "reminders.create",
  "reminders.update",
  "reminders.delete",
  "hr_settings.view",
  "hr_settings.update",
  "settings.view",
  "settings.update",
  "help_center.view",
  "accountant.dashboard.view",
  "accountant.finance.view",
  "accountant.finance.manage",
  "accountant.payments.view",
  "accountant.payments.create",
  "accountant.payments.reconcile",
  "accountant.payments.export",
  "accountant.vendors.view",
  "accountant.reports.view",
  "accountant.reports.export",
];

function buildEnterprisePermissions() {
  return ENTERPRISE_MODULE_KEYS.reduce((permissions, moduleKey) => {
    for (const action of PERMISSION_ACTIONS) {
      const key = `${moduleKey}.${action}`.toUpperCase().replace(/[^A-Z0-9]+/g, "_");
      permissions[key] = `${moduleKey}.${action}`;
    }

    return permissions;
  }, {});
}

const PERMISSIONS = Object.freeze({
  ...buildEnterprisePermissions(),
  ...Object.fromEntries(ARCHITECTURE_PERMISSIONS.map((permission) => [permission.toUpperCase().replace(/[^A-Z0-9]+/g, "_"), permission])),
  DEPARTMENT_VIEW: "department.view",
  DEPARTMENT_CREATE: "department.create",
  DEPARTMENT_UPDATE: "department.update",
  DEPARTMENT_DELETE: "department.delete",
  DEPARTMENT_ACTIVATE: "department.activate",
  DEPARTMENT_DEACTIVATE: "department.deactivate",
  DEPARTMENT_ASSIGN_HOD: "department.assign_hod",
  DEPARTMENT_ASSIGN_ASSISTANT_HOD: "department.assign_assistant_hod",
  DEPARTMENT_VIEW_EMPLOYEES: "department.view_employees",
  DEPARTMENT_TRANSFER_EMPLOYEE: "department.transfer_employee",
  DEPARTMENT_VIEW_PAYROLL: "department.view_payroll",
  DEPARTMENT_VIEW_EXPENSES: "department.view_expenses",
  DEPARTMENT_VIEW_PURCHASES: "department.view_purchases",
  DEPARTMENT_VIEW_REPORTS: "department.view_reports",
  DEPARTMENT_EXPORT: "department.export",
  DEPARTMENT_MANAGE_DOCUMENTS: "department.manage_documents",
  USERS_VIEW: "users.view",
  USERS_CREATE: "users.create",
  USERS_UPDATE: "users.update",
  USERS_DELETE: "users.delete",
  USERS_LOCK: "users.lock",
  USERS_UNLOCK: "users.unlock",
  USERS_REVOKE_SESSIONS: "users.revoke_sessions",
  USERS_RESET_PASSWORD: "users.reset_password",
  ROLES_VIEW: "roles.view",
  ROLES_CREATE: "roles.create",
  ROLES_UPDATE: "roles.update",
  ROLES_DELETE: "roles.delete",
  ROLES_MANAGE: "roles.manage",
  ROLES_ASSIGN_PERMISSIONS: "roles.assign_permissions",
  PERMISSIONS_VIEW: "permissions.view",
  PERMISSIONS_MANAGE: "permissions.manage",
  CREATE_EMPLOYEE: "employees:create",
  EDIT_EMPLOYEE: "employees:update",
  DELETE_EMPLOYEE: "employees:delete",
  VIEW_EMPLOYEE: "employees:view",
  MANAGE_DEPARTMENTS: "departments:manage",
  ASSIGN_TASKS: "tasks:assign",
  DELETE_TASKS: "tasks:delete",
  APPROVE_LEAVE: "leave:approve",
  REJECT_LEAVE: "leave:reject",
  LEAVE_VIEW: "leave.view",
  LEAVE_CREATE: "leave.create",
  LEAVE_APPROVE: "leave.approve",
  LEAVE_REJECT: "leave.reject",
  LEAVE_CANCEL: "leave.cancel",
  LEAVE_WITHDRAW: "leave.withdraw",
  LEAVE_MANAGE_TYPES: "leave.manage_types",
  LEAVE_MANAGE_POLICIES: "leave.manage_policies",
  LEAVE_MANAGE_BALANCES: "leave.manage_balances",
  LEAVE_VIEW_ALL: "leave.view_all",
  LEAVE_VIEW_DEPARTMENT: "leave.view_department",
  LEAVE_VIEW_OWN: "leave.view_own",
  LEAVE_EXPORT: "leave.export",
  LEAVE_REPORTS: "leave.reports",
  MEETING_VIEW: "meeting.view",
  MEETING_VIEW_ALL: "meeting.view_all",
  MEETING_CREATE: "meeting.create",
  MEETING_UPDATE: "meeting.update",
  MEETING_CANCEL: "meeting.cancel",
  MEETING_POSTPONE: "meeting.postpone",
  MEETING_MANAGE_PARTICIPANTS: "meeting.manage_participants",
  MEETING_MANAGE_AGENDA: "meeting.manage_agenda",
  MEETING_MANAGE_MINUTES: "meeting.manage_minutes",
  MEETING_MANAGE_ATTENDANCE: "meeting.manage_attendance",
  MEETING_MANAGE_ACTION_ITEMS: "meeting.manage_action_items",
  MEETING_MANAGE_TYPES: "meeting.manage_types",
  MEETING_MANAGE_ROOMS: "meeting.manage_rooms",
  MEETING_VIEW_REPORTS: "meeting.view_reports",
  MEETING_EXPORT: "meeting.export",
  TARGET_VIEW: "target.view",
  TARGET_VIEW_ALL: "target.view_all",
  TARGET_CREATE: "target.create",
  TARGET_UPDATE: "target.update",
  TARGET_DELETE: "target.delete",
  TARGET_ASSIGN: "target.assign",
  TARGET_UPDATE_PROGRESS: "target.update_progress",
  TARGET_MANAGE_MILESTONES: "target.manage_milestones",
  TARGET_MANAGE_REVIEWS: "target.manage_reviews",
  TARGET_VIEW_REPORTS: "target.view_reports",
  TARGET_EXPORT: "target.export",
  PAYROLL_VIEW: "payroll.view",
  PAYROLL_VIEW_ALL: "payroll.view_all",
  PAYROLL_CREATE: "payroll.create",
  PAYROLL_CALCULATE: "payroll.calculate",
  PAYROLL_UPDATE: "payroll.update",
  PAYROLL_APPROVE: "payroll.approve",
  PAYROLL_REJECT: "payroll.reject",
  PAYROLL_PROCESS_PAYMENT: "payroll.process_payment",
  PAYROLL_RETRY_PAYMENT: "payroll.retry_payment",
  PAYROLL_LOCK: "payroll.lock",
  PAYROLL_CANCEL: "payroll.cancel",
  PAYROLL_VIEW_PAYSLIPS: "payroll.view_payslips",
  PAYROLL_MANAGE_SALARY: "payroll.manage_salary",
  PAYROLL_MANAGE_DEDUCTIONS: "payroll.manage_deductions",
  PAYROLL_MANAGE_TAX_RULES: "payroll.manage_tax_rules",
  PAYROLL_MANAGE_STATUTORY_RULES: "payroll.manage_statutory_rules",
  PAYROLL_VIEW_REPORTS: "payroll.view_reports",
  PAYROLL_EXPORT: "payroll.export",
  PURCHASE_REQUEST_VIEW: "purchase_request.view",
  PURCHASE_REQUEST_VIEW_ALL: "purchase_request.view_all",
  PURCHASE_REQUEST_CREATE: "purchase_request.create",
  PURCHASE_REQUEST_UPDATE: "purchase_request.update",
  PURCHASE_REQUEST_SUBMIT: "purchase_request.submit",
  PURCHASE_REQUEST_REVIEW: "purchase_request.review",
  PURCHASE_REQUEST_APPROVE: "purchase_request.approve",
  PURCHASE_REQUEST_REJECT: "purchase_request.reject",
  PURCHASE_REQUEST_CANCEL: "purchase_request.cancel",
  PURCHASE_REQUEST_ASSIGN_VENDOR: "purchase_request.assign_vendor",
  PURCHASE_REQUEST_CREATE_ORDER: "purchase_request.create_order",
  PURCHASE_REQUEST_RECEIVE: "purchase_request.receive",
  PURCHASE_REQUEST_COMMENT: "purchase_request.comment",
  PURCHASE_REQUEST_UPLOAD: "purchase_request.upload",
  PURCHASE_REQUEST_VIEW_REPORTS: "purchase_request.view_reports",
  PURCHASE_REQUEST_EXPORT: "purchase_request.export",
  BILL_VIEW: "bill.view",
  BILL_VIEW_ALL: "bill.view_all",
  BILL_CREATE: "bill.create",
  BILL_UPDATE: "bill.update",
  BILL_SUBMIT: "bill.submit",
  BILL_REVIEW: "bill.review",
  BILL_APPROVE: "bill.approve",
  BILL_REJECT: "bill.reject",
  BILL_DISPUTE: "bill.dispute",
  BILL_SCHEDULE_PAYMENT: "bill.schedule_payment",
  BILL_PAY: "bill.pay",
  BILL_UPLOAD: "bill.upload",
  BILL_COMMENT: "bill.comment",
  BILL_EXPORT: "bill.export",
  BILL_DELETE: "bill.delete",
  EXPENSE_VIEW: "expense.view",
  EXPENSE_VIEW_ALL: "expense.view_all",
  EXPENSE_VIEW_TEAM: "expense.view_team",
  EXPENSE_CREATE: "expense.create",
  EXPENSE_CREATE_FOR_EMPLOYEE: "expense.create_for_employee",
  EXPENSE_UPDATE: "expense.update",
  EXPENSE_SUBMIT: "expense.submit",
  EXPENSE_REVIEW: "expense.review",
  EXPENSE_APPROVE: "expense.approve",
  EXPENSE_REJECT: "expense.reject",
  EXPENSE_CANCEL: "expense.cancel",
  EXPENSE_UPLOAD_RECEIPT: "expense.upload_receipt",
  EXPENSE_COMMENT: "expense.comment",
  EXPENSE_ADJUST: "expense.adjust",
  EXPENSE_REIMBURSE: "expense.reimburse",
  EXPENSE_EXPORT: "expense.export",
  EXPENSE_MANAGE_POLICIES: "expense.manage_policies",
  EVENT_VIEW: "event.view",
  EVENT_VIEW_ALL: "event.view_all",
  EVENT_CREATE: "event.create",
  EVENT_UPDATE: "event.update",
  EVENT_PUBLISH: "event.publish",
  EVENT_CANCEL: "event.cancel",
  EVENT_DELETE: "event.delete",
  EVENT_MANAGE_AUDIENCE: "event.manage_audience",
  EVENT_MANAGE_ATTENDANCE: "event.manage_attendance",
  EVENT_CHECKIN: "event.checkin",
  EVENT_MANAGE_SPONSORS: "event.manage_sponsors",
  EVENT_MANAGE_BUDGET: "event.manage_budget",
  EVENT_MANAGE_DOCUMENTS: "event.manage_documents",
  EVENT_EXPORT: "event.export",
  EVENT_VIEW_REPORTS: "event.view_reports",
  DISCIPLINE_VIEW: "discipline.view",
  DISCIPLINE_VIEW_ALL: "discipline.view_all",
  DISCIPLINE_VIEW_TEAM: "discipline.view_team",
  DISCIPLINE_CREATE: "discipline.create",
  DISCIPLINE_UPDATE: "discipline.update",
  DISCIPLINE_DELETE: "discipline.delete",
  DISCIPLINE_ASSIGN: "discipline.assign",
  DISCIPLINE_INVESTIGATE: "discipline.investigate",
  DISCIPLINE_ISSUE_ACTION: "discipline.issue_action",
  DISCIPLINE_APPROVE_ACTION: "discipline.approve_action",
  DISCIPLINE_RESOLVE: "discipline.resolve",
  DISCIPLINE_CLOSE: "discipline.close",
  DISCIPLINE_REOPEN: "discipline.reopen",
  DISCIPLINE_UPLOAD_EVIDENCE: "discipline.upload_evidence",
  DISCIPLINE_VIEW_EVIDENCE: "discipline.view_evidence",
  DISCIPLINE_MANAGE_HEARINGS: "discipline.manage_hearings",
  DISCIPLINE_MANAGE_APPEALS: "discipline.manage_appeals",
  DISCIPLINE_VIEW_EMPLOYEE_HISTORY: "discipline.view_employee_history",
  DISCIPLINE_EXPORT: "discipline.export",
  DISCIPLINE_VIEW_REPORTS: "discipline.view_reports",
  NYSC_INTERN_VIEW: "nysc_intern.view",
  NYSC_INTERN_VIEW_ALL: "nysc_intern.view_all",
  NYSC_INTERN_CREATE: "nysc_intern.create",
  NYSC_INTERN_UPDATE: "nysc_intern.update",
  NYSC_INTERN_DELETE: "nysc_intern.delete",
  NYSC_INTERN_ASSIGN_SUPERVISOR: "nysc_intern.assign_supervisor",
  NYSC_INTERN_MANAGE_PLACEMENT: "nysc_intern.manage_placement",
  NYSC_INTERN_EXTEND: "nysc_intern.extend",
  NYSC_INTERN_COMPLETE: "nysc_intern.complete",
  NYSC_INTERN_TERMINATE: "nysc_intern.terminate",
  NYSC_INTERN_MANAGE_DOCUMENTS: "nysc_intern.manage_documents",
  NYSC_INTERN_VIEW_DOCUMENTS: "nysc_intern.view_documents",
  NYSC_INTERN_MANAGE_ATTENDANCE: "nysc_intern.manage_attendance",
  NYSC_INTERN_MANAGE_REVIEWS: "nysc_intern.manage_reviews",
  NYSC_INTERN_VIEW_REVIEWS: "nysc_intern.view_reviews",
  NYSC_INTERN_MANAGE_EXIT: "nysc_intern.manage_exit",
  NYSC_INTERN_CONVERT_EMPLOYEE: "nysc_intern.convert_employee",
  NYSC_INTERN_EXPORT: "nysc_intern.export",
  ANNOUNCEMENT_VIEW: "announcement.view",
  ANNOUNCEMENT_CREATE: "announcement.create",
  ANNOUNCEMENT_EDIT: "announcement.edit",
  ANNOUNCEMENT_DELETE: "announcement.delete",
  ANNOUNCEMENT_PUBLISH: "announcement.publish",
  ANNOUNCEMENT_SCHEDULE: "announcement.schedule",
  ANNOUNCEMENT_ARCHIVE: "announcement.archive",
  ANNOUNCEMENT_PIN: "announcement.pin",
  ANNOUNCEMENT_VIEW_RECIPIENTS: "announcement.viewRecipients",
  ANNOUNCEMENT_VIEW_ANALYTICS: "announcement.viewAnalytics",
  REPORT_VIEW: "report.view",
  REPORT_CREATE: "report.create",
  REPORT_EDIT: "report.edit",
  REPORT_DELETE: "report.delete",
  REPORT_EXPORT: "report.export",
  REPORT_VIEW_PAYROLL: "report.viewPayroll",
  REPORT_VIEW_SALARY: "report.viewSalary",
  REPORT_VIEW_EXPENSES: "report.viewExpenses",
  REPORT_VIEW_DISCIPLINE: "report.viewDiscipline",
  REPORT_VIEW_ATTENDANCE: "report.viewAttendance",
  REPORT_VIEW_EMPLOYEE_DATA: "report.viewEmployeeData",
  REPORT_VIEW_ANALYTICS: "report.viewAnalytics",
  SYSTEM_VIEW: "system.view",
  SYSTEM_MANAGE: "system.manage",
  SYSTEM_SETTINGS_UPDATE: "system.settings.update",
  SYSTEM_MAINTENANCE_MANAGE: "system.maintenance.manage",
  SYSTEM_HEALTH_VIEW: "system.health.view",
  SYSTEM_SUPER_ADMIN: "system.super_admin",
  MANAGE_SALARY: "salary:manage",
  MANAGE_PROMOTIONS: "promotions:manage",
  MANAGE_MEETINGS: "meetings:manage",
  VIEW_REPORTS: "reports:view",
  MANAGE_REPORTS: "reports:manage",
  MANAGE_SETTINGS: "settings:manage",
  BACKUP: "backup:manage",
  RESTORE: "backup:restore",
  VIEW_AUDIT_LOGS: "audit:view",
  MANAGE_ROLES: "roles:manage",
  MANAGE_PERMISSIONS: "permissions:manage",
  SYSTEM_CONFIGURATION: "system:configure",
  VIEW_DASHBOARD: "dashboard:view",
  MANAGE_ATTENDANCE: "attendance:manage",
  MANAGE_ANNOUNCEMENTS: "announcements:manage",
  MANAGE_NOTIFICATIONS: "notifications:manage",
  MANAGE_FILES: "files:manage",
  GLOBAL_SEARCH: "search:global",
});

const ROLE_DEFINITIONS = Object.freeze({
  superadmin: {
    key: "superadmin",
    name: "Super Admin",
    rank: 1,
    permissions: Object.values(PERMISSIONS),
  },
  admin: {
    key: "admin",
    name: "Admin",
    rank: 2,
    permissions: Object.values(PERMISSIONS).filter((permission) => permission !== PERMISSIONS.RESTORE),
  },
  hr: {
    key: "hr",
    name: "HR",
    rank: 3,
    permissions: [
      "dashboard:view",
      "overview.view",
      "employees.view",
      "employees.create",
      "employees.update",
      "employees.archive",
      "employees.documents.view",
      "employees.documents.create",
      "employees.documents.update",
      "employees.documents.delete",
      "employee_documents.view",
      "employee_documents.create",
      "employee_documents.update",
      "employee_documents.delete",
      "employee_exits.view",
      "employee_exits.create",
      "employee_exits.update",
      "employee_exits.approve",
      "employee_exits.complete",
      "employee_exits.cancel",
      "onboarding.view",
      "onboarding.create",
      "onboarding.update",
      "onboarding.review",
      "onboarding.approve",
      "confirmation.view",
      "confirmation.review",
      "confirmation.approve",
      "confirmation.extend",
      "departments.view",
      "department.view",
      "department.view_employees",
      "positions.view",
      "leave.view",
      "leave.view_all",
      "leave.create",
      "leave.approve",
      "leave.reject",
      "leave.cancel",
      "leave.reports",
      "attendance.view",
      "promotions.view",
      "promotions.create",
      "promotions.approve",
      "promotions.reject",
      "promotions.manage",
      "salary.view",
      "salary.create",
      "salary.update",
      "salary.review",
      "salary.approve",
      "salary.reject",
      "salary_increments.view",
      "salary_increments.create",
      "salary_increments.approve",
      "salary_increments.reject",
      "discipline.view",
      "discipline.view_all",
      "discipline.create",
      "discipline.update",
      "discipline.close",
      "discipline.resolve",
      "nysc_intern.view",
      "nysc_intern.view_all",
      "nysc_intern.create",
      "nysc_intern.update",
      "nysc_intern.assign_supervisor",
      "nysc_intern.manage_placement",
      "nysc_intern.extend",
      "nysc_intern.complete",
      "nysc_intern.terminate",
      "nysc_intern.manage_documents",
      "nysc_intern.view_documents",
      "nysc_intern.manage_attendance",
      "nysc_intern.manage_reviews",
      "nysc_intern.view_reviews",
      "nysc_intern.manage_exit",
      "nysc_intern.convert_employee",
      "nysc_intern.export",
      "attendance.view",
      "reports.view",
      "reports.export",
      "report.view",
      "report.viewAttendance",
      "report.export",
      "notifications.view",
      "audit_logs.view",
      "hr_settings.view",
      "hr_settings.update",
      "settings.view",
      "settings.update",
      "help_center.view",
      "profile.view",
      "profile.update",
    ],
  },
  manager: {
    key: "manager",
    name: "Manager",
    rank: 3,
    permissions: [
      "dashboard:view",
      "overview.view",
      "employees.view",
      "employees.update",
      "departments.view",
      "positions.view",
      "leave.view",
      "leave.create",
      "leave.approve",
      "leave.reject",
      "leave.view_team",
      "attendance.view",
      "attendance.manage",
      "attendance.correct",
      "attendance.locations.view",
      "attendance.locations.manage",
      "attendance.schedules.view",
      "attendance.schedules.manage",
      "performance.view",
      "performance.create",
      "performance.review",
      "promotions.view",
      "promotions.create",
      "salary.view",
      "salary_increments.view",
      "salary_increments.create",
      "meetings.view",
      "meetings.create",
      "meetings.update",
      "tasks.view",
      "tasks.create",
      "tasks.assign",
      "tasks.update",
      "targets.view",
      "targets.create",
      "targets.assign",
      "targets.update",
      "finance.view",
      "finance.create",
      "finance.approve",
      "procurement.view",
      "procurement.create",
      "procurement.approve",
      "purchases.view",
      "purchases.create",
      "purchases.approve",
      "purchases.reject",
      "expenses.view",
      "expenses.create",
      "expenses.approve",
      "expenses.reject",
      "bills.view",
      "bills.create",
      "bills.approve",
      "events.view",
      "events.create",
      "events.update",
      "discipline.view",
      "discipline.create",
      "discipline.update",
      "discipline.close",
      "reports.view",
      "report.view",
      "report.viewAttendance",
      "notifications.view",
      "audit_logs.view",
      "settings.view",
      "settings.update",
      "help_center.view",
      "profile.view",
      "profile.update",
    ],
  },
  hod: {
    key: "hod",
    name: "HOD",
    rank: 3,
    description: "Head of Department",
    permissions: [
      "dashboard:view",
      "overview.view",
      "employees.view",
      "departments.view",
      "leave.view",
      "leave.create",
      "leave.approve",
      "leave.reject",
      "leave.view_team",
      "performance.view",
      "performance.create",
      "performance.review",
      "promotions.view",
      "promotions.create",
      "salary.view",
      "salary_increments.view",
      "salary_increments.create",
      "meetings.view",
      "meetings.create",
      "meetings.update",
      "tasks.view",
      "tasks.create",
      "tasks.assign",
      "tasks.update",
      "targets.view",
      "targets.create",
      "targets.assign",
      "targets.update",
      "finance.view",
      "finance.create",
      "procurement.view",
      "procurement.create",
      "purchases.view",
      "purchases.create",
      "expenses.view",
      "expenses.create",
      "events.view",
      "events.create",
      "events.update",
      "discipline.view",
      "discipline.create",
      "discipline.update",
      "discipline.close",
      "reports.view",
      "notifications.view",
      "audit_logs.view",
      "settings.view",
      "settings.update",
      "help_center.view",
      "profile.view",
      "profile.update",
    ],
  },
  secretary: {
    key: "secretary",
    name: "Secretary",
    rank: 4,
    permissions: [
      "dashboard:view",
      "overview.view",
      "secretary.dashboard.view",
      "email_requests.view",
      "email_requests.create",
      "email_requests.update",
      "email_requests.review",
      "email_requests.approve",
      "email_requests.reject",
      "email_requests.cancel",
      "email_requests.retry",
      "email_requests.check_availability",
      "email_requests.create_company_email",
      "email_requests.follow_up",
      "company_email.view",
      "company_email.search",
      "company_email.edit_address",
      "company_email.suspend",
      "company_email.reactivate",
      "company_email.request_deactivation",
      "company_email.view_history",
      "calendar.view",
      "calendar.create",
      "calendar.update",
      "calendar.delete",
      "meetings.view",
      "meetings.create",
      "meetings.update",
      "meetings.cancel",
      "meetings.reschedule",
      "meeting.view",
      "meeting.create",
      "meeting.update",
      "meeting.cancel",
      "meeting.manage_participants",
      "management_tasks.view",
      "management_tasks.create",
      "management_tasks.update",
      "management_tasks.assign",
      "tasks.view",
      "tasks.create",
      "tasks.update",
      "tasks.assign",
      "reminders.view",
      "reminders.create",
      "reminders.update",
      "reminders.delete",
      "notifications.view",
      "audit_logs.view",
      "profile.view",
      "profile.update",
    ],
  },
  accountant: {
    key: "accountant",
    name: "Accountant",
    rank: 4,
    permissions: [
      "dashboard:view",
      "overview.view",
      "accountant.dashboard.view",
      "accountant.finance.view",
      "accountant.finance.manage",
      "accountant.payments.view",
      "accountant.payments.create",
      "accountant.payments.reconcile",
      "accountant.payments.export",
      "accountant.vendors.view",
      "accountant.reports.view",
      "accountant.reports.export",
      "finance.view",
      "finance.create",
      "finance.approve",
      "payroll.view",
      "payroll.view_all",
      "payroll.process_payment",
      "payroll.view_payslips",
      "payroll.manage_deductions",
      "payroll.view_reports",
      "payroll.export",
      "salary.view",
      "salary.update",
      "salary_increments.view",
      "salary_increments.approve",
      "purchases.view",
      "purchases.approve",
      "procurement.view",
      "purchase_request.view",
      "purchase_request.approve",
      "purchase_request.export",
      "bills.view",
      "bill.view",
      "bill.create",
      "bill.update",
      "bill.review",
      "bill.approve",
      "bill.schedule_payment",
      "bill.pay",
      "bill.comment",
      "bill.upload",
      "bill.export",
      "expenses.view",
      "expenses.approve",
      "expenses.reject",
      "expenses.manage",
      "expenses.export",
      "expense.view",
      "expense.approve",
      "expense.reject",
      "expense.reimburse",
      "expense.export",
      "vendors.view",
      "reports.view",
      "reports.export",
      "notifications.view",
      "audit_logs.view",
      "settings.view",
      "settings.update",
      "help_center.view",
      "profile.view",
      "profile.update",
      "attendance.check_in",
    ],
  },
  department_manager: {
    key: "department_manager",
    name: "Department Manager",
    rank: 3,
    permissions: [
      PERMISSIONS.VIEW_DASHBOARD,
      PERMISSIONS.VIEW_EMPLOYEE,
      PERMISSIONS.EDIT_EMPLOYEE,
      PERMISSIONS.MANAGE_DEPARTMENTS,
      PERMISSIONS.ASSIGN_TASKS,
      PERMISSIONS.APPROVE_LEAVE,
      PERMISSIONS.REJECT_LEAVE,
      PERMISSIONS.LEAVE_VIEW_OWN,
      PERMISSIONS.LEAVE_CREATE,
      PERMISSIONS.LEAVE_WITHDRAW,
      PERMISSIONS.LEAVE_VIEW_DEPARTMENT,
      PERMISSIONS.LEAVE_APPROVE,
      PERMISSIONS.LEAVE_REJECT,
      PERMISSIONS.MANAGE_MEETINGS,
      PERMISSIONS.MEETING_VIEW,
      PERMISSIONS.MEETING_VIEW_ALL,
      PERMISSIONS.MEETING_CREATE,
      PERMISSIONS.MEETING_UPDATE,
      PERMISSIONS.MEETING_CANCEL,
      PERMISSIONS.MEETING_POSTPONE,
      PERMISSIONS.MEETING_MANAGE_PARTICIPANTS,
      PERMISSIONS.MEETING_MANAGE_AGENDA,
      PERMISSIONS.MEETING_MANAGE_MINUTES,
      PERMISSIONS.MEETING_MANAGE_ATTENDANCE,
      PERMISSIONS.MEETING_MANAGE_ACTION_ITEMS,
      PERMISSIONS.MEETING_VIEW_REPORTS,
      PERMISSIONS.TARGET_VIEW,
      PERMISSIONS.TARGET_VIEW_ALL,
      PERMISSIONS.TARGET_CREATE,
      PERMISSIONS.TARGET_UPDATE,
      PERMISSIONS.TARGET_DELETE,
      PERMISSIONS.TARGET_ASSIGN,
      PERMISSIONS.TARGET_UPDATE_PROGRESS,
      PERMISSIONS.TARGET_MANAGE_MILESTONES,
      PERMISSIONS.TARGET_MANAGE_REVIEWS,
      PERMISSIONS.TARGET_VIEW_REPORTS,
      PERMISSIONS.TARGET_EXPORT,
      PERMISSIONS.PAYROLL_VIEW,
      PERMISSIONS.PAYROLL_VIEW_ALL,
      PERMISSIONS.PAYROLL_CREATE,
      PERMISSIONS.PAYROLL_CALCULATE,
      PERMISSIONS.PAYROLL_UPDATE,
      PERMISSIONS.PAYROLL_APPROVE,
      PERMISSIONS.PAYROLL_REJECT,
      PERMISSIONS.PAYROLL_PROCESS_PAYMENT,
      PERMISSIONS.PAYROLL_RETRY_PAYMENT,
      PERMISSIONS.PAYROLL_LOCK,
      PERMISSIONS.PAYROLL_CANCEL,
      PERMISSIONS.PAYROLL_VIEW_PAYSLIPS,
      PERMISSIONS.PAYROLL_MANAGE_SALARY,
      PERMISSIONS.PAYROLL_MANAGE_DEDUCTIONS,
      PERMISSIONS.PAYROLL_MANAGE_TAX_RULES,
      PERMISSIONS.PAYROLL_MANAGE_STATUTORY_RULES,
      PERMISSIONS.PAYROLL_VIEW_REPORTS,
      PERMISSIONS.PAYROLL_EXPORT,
      PERMISSIONS.PURCHASE_REQUEST_VIEW,
      PERMISSIONS.PURCHASE_REQUEST_VIEW_ALL,
      PERMISSIONS.PURCHASE_REQUEST_CREATE,
      PERMISSIONS.PURCHASE_REQUEST_UPDATE,
      PERMISSIONS.PURCHASE_REQUEST_SUBMIT,
      PERMISSIONS.PURCHASE_REQUEST_REVIEW,
      PERMISSIONS.PURCHASE_REQUEST_APPROVE,
      PERMISSIONS.PURCHASE_REQUEST_REJECT,
      PERMISSIONS.PURCHASE_REQUEST_CANCEL,
      PERMISSIONS.PURCHASE_REQUEST_ASSIGN_VENDOR,
      PERMISSIONS.PURCHASE_REQUEST_CREATE_ORDER,
      PERMISSIONS.PURCHASE_REQUEST_RECEIVE,
      PERMISSIONS.PURCHASE_REQUEST_COMMENT,
      PERMISSIONS.PURCHASE_REQUEST_UPLOAD,
      PERMISSIONS.PURCHASE_REQUEST_VIEW_REPORTS,
      PERMISSIONS.PURCHASE_REQUEST_EXPORT,
      PERMISSIONS.BILL_VIEW,
      PERMISSIONS.BILL_CREATE,
      PERMISSIONS.BILL_UPDATE,
      PERMISSIONS.BILL_SUBMIT,
      PERMISSIONS.BILL_REVIEW,
      PERMISSIONS.BILL_APPROVE,
      PERMISSIONS.BILL_REJECT,
      PERMISSIONS.BILL_DISPUTE,
      PERMISSIONS.BILL_UPLOAD,
      PERMISSIONS.BILL_COMMENT,
      PERMISSIONS.BILL_EXPORT,
      PERMISSIONS.EXPENSE_VIEW,
      PERMISSIONS.EXPENSE_VIEW_TEAM,
      PERMISSIONS.EXPENSE_CREATE,
      PERMISSIONS.EXPENSE_UPDATE,
      PERMISSIONS.EXPENSE_SUBMIT,
      PERMISSIONS.EXPENSE_REVIEW,
      PERMISSIONS.EXPENSE_APPROVE,
      PERMISSIONS.EXPENSE_REJECT,
      PERMISSIONS.EXPENSE_CANCEL,
      PERMISSIONS.EXPENSE_UPLOAD_RECEIPT,
      PERMISSIONS.EXPENSE_COMMENT,
      PERMISSIONS.EXPENSE_EXPORT,
      PERMISSIONS.EVENT_VIEW,
      PERMISSIONS.EVENT_VIEW_ALL,
      PERMISSIONS.EVENT_CREATE,
      PERMISSIONS.EVENT_UPDATE,
      PERMISSIONS.EVENT_PUBLISH,
      PERMISSIONS.EVENT_CANCEL,
      PERMISSIONS.EVENT_MANAGE_AUDIENCE,
      PERMISSIONS.EVENT_MANAGE_ATTENDANCE,
      PERMISSIONS.EVENT_CHECKIN,
      PERMISSIONS.EVENT_MANAGE_DOCUMENTS,
      PERMISSIONS.EVENT_EXPORT,
      PERMISSIONS.EVENT_VIEW_REPORTS,
      PERMISSIONS.DISCIPLINE_VIEW,
      PERMISSIONS.DISCIPLINE_VIEW_TEAM,
      PERMISSIONS.DISCIPLINE_CREATE,
      PERMISSIONS.DISCIPLINE_UPDATE,
      PERMISSIONS.DISCIPLINE_ASSIGN,
      PERMISSIONS.DISCIPLINE_INVESTIGATE,
      PERMISSIONS.DISCIPLINE_ISSUE_ACTION,
      PERMISSIONS.DISCIPLINE_RESOLVE,
      PERMISSIONS.DISCIPLINE_CLOSE,
      PERMISSIONS.DISCIPLINE_REOPEN,
      PERMISSIONS.DISCIPLINE_UPLOAD_EVIDENCE,
      PERMISSIONS.DISCIPLINE_VIEW_EVIDENCE,
      PERMISSIONS.DISCIPLINE_MANAGE_HEARINGS,
      PERMISSIONS.DISCIPLINE_MANAGE_APPEALS,
      PERMISSIONS.DISCIPLINE_VIEW_EMPLOYEE_HISTORY,
      PERMISSIONS.DISCIPLINE_EXPORT,
      PERMISSIONS.DISCIPLINE_VIEW_REPORTS,
      PERMISSIONS.NYSC_INTERN_VIEW,
      PERMISSIONS.NYSC_INTERN_VIEW_ALL,
      PERMISSIONS.NYSC_INTERN_CREATE,
      PERMISSIONS.NYSC_INTERN_UPDATE,
      PERMISSIONS.NYSC_INTERN_ASSIGN_SUPERVISOR,
      PERMISSIONS.NYSC_INTERN_MANAGE_PLACEMENT,
      PERMISSIONS.NYSC_INTERN_EXTEND,
      PERMISSIONS.NYSC_INTERN_COMPLETE,
      PERMISSIONS.NYSC_INTERN_MANAGE_DOCUMENTS,
      PERMISSIONS.NYSC_INTERN_VIEW_DOCUMENTS,
      PERMISSIONS.NYSC_INTERN_MANAGE_ATTENDANCE,
      PERMISSIONS.NYSC_INTERN_MANAGE_REVIEWS,
      PERMISSIONS.NYSC_INTERN_VIEW_REVIEWS,
      PERMISSIONS.NYSC_INTERN_MANAGE_EXIT,
      PERMISSIONS.NYSC_INTERN_EXPORT,
      PERMISSIONS.ANNOUNCEMENT_VIEW,
      PERMISSIONS.ANNOUNCEMENT_CREATE,
      PERMISSIONS.ANNOUNCEMENT_EDIT,
      PERMISSIONS.ANNOUNCEMENT_PUBLISH,
      PERMISSIONS.ANNOUNCEMENT_SCHEDULE,
      PERMISSIONS.ANNOUNCEMENT_ARCHIVE,
      PERMISSIONS.ANNOUNCEMENT_PIN,
      PERMISSIONS.ANNOUNCEMENT_VIEW_RECIPIENTS,
      PERMISSIONS.ANNOUNCEMENT_VIEW_ANALYTICS,
      PERMISSIONS.VIEW_REPORTS,
      PERMISSIONS.MANAGE_ATTENDANCE,
      PERMISSIONS.MANAGE_ANNOUNCEMENTS,
      PERMISSIONS.MANAGE_NOTIFICATIONS,
      PERMISSIONS.GLOBAL_SEARCH,
    ],
  },
  team_leader: {
    key: "team_leader",
    name: "Team Leader",
    rank: 4,
    permissions: [
      PERMISSIONS.VIEW_DASHBOARD,
      PERMISSIONS.VIEW_EMPLOYEE,
      PERMISSIONS.ASSIGN_TASKS,
      PERMISSIONS.MANAGE_MEETINGS,
      PERMISSIONS.MEETING_VIEW,
      PERMISSIONS.MEETING_CREATE,
      PERMISSIONS.MEETING_UPDATE,
      PERMISSIONS.MEETING_CANCEL,
      PERMISSIONS.MEETING_POSTPONE,
      PERMISSIONS.MEETING_MANAGE_PARTICIPANTS,
      PERMISSIONS.MEETING_MANAGE_AGENDA,
      PERMISSIONS.MEETING_MANAGE_MINUTES,
      PERMISSIONS.MEETING_MANAGE_ATTENDANCE,
      PERMISSIONS.MEETING_MANAGE_ACTION_ITEMS,
      PERMISSIONS.TARGET_VIEW,
      PERMISSIONS.TARGET_CREATE,
      PERMISSIONS.TARGET_UPDATE,
      PERMISSIONS.TARGET_ASSIGN,
      PERMISSIONS.TARGET_UPDATE_PROGRESS,
      PERMISSIONS.TARGET_MANAGE_MILESTONES,
      PERMISSIONS.TARGET_VIEW_REPORTS,
      PERMISSIONS.PAYROLL_VIEW,
      PERMISSIONS.PAYROLL_VIEW_PAYSLIPS,
      PERMISSIONS.PAYROLL_VIEW_REPORTS,
      PERMISSIONS.PURCHASE_REQUEST_VIEW,
      PERMISSIONS.PURCHASE_REQUEST_CREATE,
      PERMISSIONS.PURCHASE_REQUEST_UPDATE,
      PERMISSIONS.PURCHASE_REQUEST_SUBMIT,
      PERMISSIONS.PURCHASE_REQUEST_REVIEW,
      PERMISSIONS.PURCHASE_REQUEST_APPROVE,
      PERMISSIONS.PURCHASE_REQUEST_REJECT,
      PERMISSIONS.PURCHASE_REQUEST_CANCEL,
      PERMISSIONS.PURCHASE_REQUEST_COMMENT,
      PERMISSIONS.PURCHASE_REQUEST_UPLOAD,
      PERMISSIONS.PURCHASE_REQUEST_VIEW_REPORTS,
      PERMISSIONS.BILL_VIEW,
      PERMISSIONS.BILL_CREATE,
      PERMISSIONS.BILL_SUBMIT,
      PERMISSIONS.BILL_REVIEW,
      PERMISSIONS.BILL_APPROVE,
      PERMISSIONS.BILL_REJECT,
      PERMISSIONS.BILL_COMMENT,
      PERMISSIONS.BILL_UPLOAD,
      PERMISSIONS.EXPENSE_VIEW,
      PERMISSIONS.EXPENSE_VIEW_TEAM,
      PERMISSIONS.EXPENSE_CREATE,
      PERMISSIONS.EXPENSE_UPDATE,
      PERMISSIONS.EXPENSE_SUBMIT,
      PERMISSIONS.EXPENSE_REVIEW,
      PERMISSIONS.EXPENSE_APPROVE,
      PERMISSIONS.EXPENSE_REJECT,
      PERMISSIONS.EXPENSE_CANCEL,
      PERMISSIONS.EXPENSE_UPLOAD_RECEIPT,
      PERMISSIONS.EXPENSE_COMMENT,
      PERMISSIONS.EVENT_VIEW,
      PERMISSIONS.EVENT_CREATE,
      PERMISSIONS.EVENT_UPDATE,
      PERMISSIONS.EVENT_PUBLISH,
      PERMISSIONS.EVENT_CANCEL,
      PERMISSIONS.EVENT_MANAGE_AUDIENCE,
      PERMISSIONS.EVENT_MANAGE_ATTENDANCE,
      PERMISSIONS.EVENT_CHECKIN,
      PERMISSIONS.EVENT_MANAGE_DOCUMENTS,
      PERMISSIONS.EVENT_VIEW_REPORTS,
      PERMISSIONS.DISCIPLINE_VIEW,
      PERMISSIONS.DISCIPLINE_VIEW_TEAM,
      PERMISSIONS.DISCIPLINE_CREATE,
      PERMISSIONS.DISCIPLINE_INVESTIGATE,
      PERMISSIONS.DISCIPLINE_UPLOAD_EVIDENCE,
      PERMISSIONS.DISCIPLINE_VIEW_EVIDENCE,
      PERMISSIONS.DISCIPLINE_VIEW_EMPLOYEE_HISTORY,
      PERMISSIONS.DISCIPLINE_VIEW_REPORTS,
      PERMISSIONS.NYSC_INTERN_VIEW,
      PERMISSIONS.NYSC_INTERN_ASSIGN_SUPERVISOR,
      PERMISSIONS.NYSC_INTERN_MANAGE_ATTENDANCE,
      PERMISSIONS.NYSC_INTERN_MANAGE_REVIEWS,
      PERMISSIONS.NYSC_INTERN_VIEW_REVIEWS,
      PERMISSIONS.NYSC_INTERN_VIEW_DOCUMENTS,
      PERMISSIONS.ANNOUNCEMENT_VIEW,
      PERMISSIONS.VIEW_REPORTS,
      PERMISSIONS.MANAGE_ATTENDANCE,
      PERMISSIONS.GLOBAL_SEARCH,
    ],
  },
  employee: {
    key: "employee",
    name: "Employee",
    rank: 5,
    permissions: [
      PERMISSIONS.VIEW_DASHBOARD,
      PERMISSIONS.VIEW_EMPLOYEE,
      "attendance.check_in",
      PERMISSIONS.LEAVE_VIEW_OWN,
      PERMISSIONS.LEAVE_CREATE,
      PERMISSIONS.LEAVE_WITHDRAW,
      PERMISSIONS.MANAGE_MEETINGS,
      PERMISSIONS.MEETING_VIEW,
      PERMISSIONS.TARGET_VIEW,
      PERMISSIONS.TARGET_UPDATE_PROGRESS,
      PERMISSIONS.PAYROLL_VIEW_PAYSLIPS,
      PERMISSIONS.PURCHASE_REQUEST_VIEW,
      PERMISSIONS.PURCHASE_REQUEST_CREATE,
      PERMISSIONS.PURCHASE_REQUEST_SUBMIT,
      PERMISSIONS.PURCHASE_REQUEST_CANCEL,
      PERMISSIONS.PURCHASE_REQUEST_COMMENT,
      PERMISSIONS.PURCHASE_REQUEST_UPLOAD,
      PERMISSIONS.BILL_VIEW,
      PERMISSIONS.BILL_COMMENT,
      PERMISSIONS.BILL_UPLOAD,
      PERMISSIONS.EXPENSE_VIEW,
      PERMISSIONS.EXPENSE_CREATE,
      PERMISSIONS.EXPENSE_UPDATE,
      PERMISSIONS.EXPENSE_SUBMIT,
      PERMISSIONS.EXPENSE_CANCEL,
      PERMISSIONS.EXPENSE_UPLOAD_RECEIPT,
      PERMISSIONS.EXPENSE_COMMENT,
      PERMISSIONS.EVENT_VIEW,
      PERMISSIONS.EVENT_CHECKIN,
      PERMISSIONS.DISCIPLINE_VIEW,
      PERMISSIONS.NYSC_INTERN_VIEW,
      PERMISSIONS.NYSC_INTERN_VIEW_DOCUMENTS,
      PERMISSIONS.NYSC_INTERN_VIEW_REVIEWS,
      PERMISSIONS.ANNOUNCEMENT_VIEW,
      PERMISSIONS.GLOBAL_SEARCH,
    ],
  },
  nysc_intern: {
    key: "nysc_intern",
    name: "NYSC/Intern",
    rank: 6,
    permissions: [
      PERMISSIONS.VIEW_DASHBOARD,
      "profile.view",
      "profile.update",
      "tasks.view",
      "tasks.update",
      "attendance.check_in",
      PERMISSIONS.MEETING_VIEW,
      PERMISSIONS.TARGET_VIEW,
      PERMISSIONS.TARGET_UPDATE_PROGRESS,
      PERMISSIONS.NYSC_INTERN_VIEW,
      PERMISSIONS.NYSC_INTERN_VIEW_DOCUMENTS,
      PERMISSIONS.NYSC_INTERN_VIEW_REVIEWS,
      PERMISSIONS.ANNOUNCEMENT_VIEW,
    ],
  },
  intern: {
    key: "intern",
    name: "Intern",
    rank: 6,
    permissions: [
      PERMISSIONS.VIEW_DASHBOARD,
      "profile.view",
      "profile.update",
      "tasks.view",
      "tasks.update",
      "attendance.check_in",
      PERMISSIONS.MEETING_VIEW,
      PERMISSIONS.TARGET_VIEW,
      PERMISSIONS.TARGET_UPDATE_PROGRESS,
      PERMISSIONS.NYSC_INTERN_VIEW,
      PERMISSIONS.NYSC_INTERN_VIEW_DOCUMENTS,
      PERMISSIONS.NYSC_INTERN_VIEW_REVIEWS,
      PERMISSIONS.ANNOUNCEMENT_VIEW,
    ],
  },
});

function getRoleDefinition(role) {
  return ROLE_DEFINITIONS[String(role || "").toLowerCase()] || null;
}

function getRolePermissions(role) {
  const definition = getRoleDefinition(role);
  return definition ? definition.permissions : [];
}

function hasPermission(user, permission) {
  if (!user) {
    return false;
  }

  const rolePermissions = getRolePermissions(user.role);
  const directPermissions = Array.isArray(user.permissions) ? user.permissions : [];
  return rolePermissions.includes(permission) || directPermissions.includes(permission);
}

module.exports = { PERMISSIONS, ROLE_DEFINITIONS, getRoleDefinition, getRolePermissions, hasPermission };
